name: BiomeCreator
main: ddev.dementisimus.biomecreator.BiomeCreatorPlugin
author: dementisimus
version: ${project.version}
website: dementisimus.dev
api-version: 1.17

load: STARTUP
depend: [ CoreAPI ]
softdepend: [ CoreAPI-Dependencies ]
